sources:
  - Wittgenstein.glyphs
familyName: Wittgenstein

stat:
  Wittgenstein[wght].ttf:
  - name: Weight
    tag: wght
    values:
     - name: Regular
       value: 400
     - name: Bold
       value: 700
